### PR TITLE
Ksathwik03 completed task-02

### PR DESCRIPTION
**Pull request by Ksathwik03**
i completed the task and i used media queries in such a way that it supports mobile

### CODE REVIEW

**Comment by garvitchittora** [comment]
@Ksathwik03 not responsive

**Comment by Ksathwik03** [comment]
@garvitchittora sir could you please join discord i have doubts please

**Comment by Ksathwik03** [comment]
> @Ksathwik03 not responsive

i made it responsive sir

**Comment by garvitchittora** [comment]
@Ksathwik03 still not responsive!!

**Comment by Ksathwik03** [comment]
> @Ksathwik03 still not responsive!!

sir i do not know why is it happening sir i sent the pictures of my website which is responsive to your discord dm could please verify sir .
thanking you

**Comment by Ksathwik03** [comment]
Screenshot (25)
Screenshot (23)
Screenshot (24)
Screenshot (27)
Screenshot (26)
i am sending the screen shots even here sir

**Comment by Ksathwik03** [comment]
> @Ksathwik03 still not responsive!!

i made some changes sir

**Review by om1621 — COMMENTED** [review]
Image is not responsive , navbar can be improved

**Pull request merged**
