### PR TITLE
Task 1 completed

### PR DESCRIPTION
**Pull request by ritwikrajput**
Sir please merge this......

### CODE REVIEW

**Comment by garvitchittora** [comment]
@kaneki-ken260 head tag missing

**Comment by ritwikrajput** [comment]
sir i have added another file in my repository please review that

**Comment by ritwikrajput** [comment]
@garvitchittora  sir i have added another file in my repository named task1.html before the deadline so please review that

**Comment by sarthakm21** [comment]
Multiple tags closed in the wrong way.
</option> is the correct way, not <option/>

**Comment by garvitchittora** [comment]
pls, make the necessary changes(told above) in your repo before 12 pm otherwise we will close this PR. When you have implemented the changes then comment here only.

**Comment by ritwikrajput** [comment]
Sir please check that is it fine now??
Sorry sir for the delay

**Pull request merged**
