### PR TITLE
completed webd task 1

### PR DESCRIPTION
**Pull request by Ayushi181**
completed webd task 1

### CODE REVIEW

**Comment by garvitchittora** [comment]
@Ayushi181 correct this tag <!doctype>

**Comment by Ayushi181** [comment]
Sir how to correct the tab . I literally don't have idea . Please tell me
what to do.

**Comment by garvitchittora** [comment]
use this `<!DOCTYPE html>` in place of <!doctype>

**Comment by Ayushi181** [comment]
Sir after changing what we have to do .

**Comment by Ayushi181** [comment]
Sir I have done now ..plz check

**Comment by sarthakm21** [comment]
Missing closing " on line 26.
Numeric values aren't wrapped in quotes.
footer tag should be in the body tag

**Comment by Ayushi181** [comment]
Sir I again corrected. Actually my code was running and it was sawing the
same registration form so thought of no  mistake. Now please check and
merge.

**Pull request merged**
