### PR TITLE
completed webd task 1

### PR DESCRIPTION
**Pull request by hardikarora2**
completed webd task 1

### CODE REVIEW

**Comment by garvitchittora** [comment]
@hardikarora2 footer should be inside the body tag

**Comment by garvitchittora** [comment]
@hardikarora2 pls make the necessary changes(told above) in your repo before 12 pm otherwise we will close this PR. When you have implemented the changes then comment here only.

**Comment by garvitchittora** [comment]
@hardikarora2 copied!!

**Comment by hardikarora2** [comment]
respected sir
i didn't copy the code from adityaraj723 instead i helped him in doing the
task. I had submitted earlier to him.
his pr number was 148 and mine was 137

**Pull request closed without merging**
