### PR TITLE
Rakeshtitty123 completed Task-1 of WebD

### PR DESCRIPTION
**Pull request by echoCodeScript**

### CODE REVIEW

**Comment by garvitchittora** [comment]
@Rakeshtitty123 make .html file of code not .md file

**Comment by sarthakm21** [comment]
@Rakeshtitty123 closing HTML tag missing and double quotes missing in the last div's style attribute

**Comment by garvitchittora** [comment]
pls, make the necessary changes(told above) in your repo before 12 pm otherwise we will close this PR. When you have implemented the changes then comment here only.

**Comment by echoCodeScript** [comment]
@garvitchittora  Sir,I have commited the necessary changes in my repo

**Comment by garvitchittora** [comment]
@Rakeshtitty123 remove Rakeshtitty123.json.docx and Task 1.html from your forked repo

**Pull request closed without merging**
