### PR TITLE
Completed task-1

### PR DESCRIPTION
**Pull request by Nihar-code**

### CODE REVIEW

**Comment by garvitchittora** [comment]
@Nihar-code your repo is empty

**Comment by Nihar-code** [comment]
Sir maine html ke extension se file save kare the jo notepad par banaye the aur wage file apne repo main dal de the ab aap bata dijiye kya galte ho gaye

**Comment by Nihar-code** [comment]
Bhaiya maine karde hain upload,ab mujhe phir se pull request bhejne padege kya

**Comment by Nihar-code** [comment]
Maine apne repo main commet kar diya hain,jo main pehle bhul gaya tha isliye mere repo main empty dikha raha tha

**Comment by sarthakm21** [comment]
href attribute empty in anchor tags(<a>)

**Comment by garvitchittora** [comment]
pls, make the necessary changes(told above) in your repo before 12 pm otherwise we will close this PR. When you have implemented the changes then comment here only.

**Comment by Nihar-code** [comment]
Garvit sir maine apne purane file ke href attribute main google ka url dal diya hain aur ek dusre file upload kar de hain jisme necessary changes hain.

**Pull request merged**
