### PR TITLE
Solved task 1

### PR DESCRIPTION
**Pull request by bipulkmr-crypto**

### CODE REVIEW

**Comment by garvitchittora** [comment]
@bipulkmr-crypto HTML file wrong structure, **header tag should be inside the body tag**.

**Comment by bipulkmr-crypto** [comment]
Solved the issue

**Comment by garvitchittora** [comment]
head tag missing in HTML

**Comment by bipulkmr-crypto** [comment]
> head tag missing in HTML

image
Sir it is there inside the body

**Comment by garvitchittora** [comment]
The head element is placed between the HTML tag and the body tag.

**Comment by bipulkmr-crypto** [comment]
Sir i had to do that because then the heading was not going below the header links

**Comment by garvitchittora** [comment]
= missing btw href and ", now pls check your HTML completely then make a comment!!

**Comment by garvitchittora** [comment]
pls, make the necessary changes(told above) in your repo before 12 pm otherwise we will close this PR. When you have implemented the changes then comment here only.

**Comment by bipulkmr-crypto** [comment]
Sir please check now

**Comment by garvitchittora** [comment]
> = missing btw href and ", now pls check your HTML completely then make a comment!!

till now not solved so closing your PR.

**Pull request closed without merging**
