### PR TITLE
completed task-1

### PR DESCRIPTION
**Pull request by PoojithaMiriyala**

### CODE REVIEW

**Comment by garvitchittora** [comment]
@PoojithaMiriyala close html tag

**Comment by garvitchittora** [comment]
pls, make the necessary changes(told above) in your repo before 12 pm otherwise we will close this PR. When you have implemented the changes then comment here only.

**Comment by PoojithaMiriyala** [comment]
@garvitchittora  I have updated html file

**Comment by garvitchittora** [comment]
@PoojithaMiriyala merging for now but their are few problem in code style="color:black;text-align:left" and no need of span in nav.

**Pull request merged**
