### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by narayanaditya1007**
Jai webD

### CODE REVIEW

**Comment by infern018** [comment]
file name should be your **github username**.json

**Comment by narayanaditya1007** [comment]
uploaded once again with corrected name , now please merge , sir

**Comment by garvitchittora** [comment]
@narayanaditya1007 remove Narayan.json + fontawesome icons missing

**Comment by garvitchittora** [comment]
pls, make the necessary changes(told above) in your repo before 12 pm otherwise we will close this PR. When you have implemented the changes then comment here only.

**Pull request closed without merging**
