### PR TITLE
AshokMalhotra23 completed task-2

### PR DESCRIPTION
**Pull request by AshokMalhotra23**

### CODE REVIEW

**Comment by garvitchittora** [comment]
@AshokMalhotra23  hey, please add all the elements that were given in Figma.

**Comment by AshokMalhotra23** [comment]
> @AshokMalhotra23 hey, please add all the elements that were given in Figma.

Sir I made the required changes. Please check again.

**Comment by garvitchittora** [comment]
@AshokMalhotra23 Geekhaven logo missing and the mobile design is different from what you made. please check the Figma link once again.

**Comment by AshokMalhotra23** [comment]
> @AshokMalhotra23 Geekhaven logo missing and the mobile design is different from what you made. please check the Figma link once again.

Sir could you please check now , I have made the required changes.

**Pull request merged**
