### PR TITLE
task2 completed

### PR DESCRIPTION
**Pull request by shivamhaz444**

### CODE REVIEW

**Comment by infern018** [comment]
Great work!

**Comment by infern018** [comment]
Your page is not exactly as per the figma given though, in WebD its an important skill to realize a design, hence the challenge was given...

**Comment by shivamhaz444** [comment]
It was a  portfolio website and we have not got instructions to create exactly the same website, so I thought to design  my own portfolio website in my way

**Comment by shivamhaz444** [comment]
points given to me wasn't fair enough

**Comment by shivamhaz444** [comment]
as i have worked 3 days continously to first learn and then make this website

**Pull request merged**
