### PR TITLE
task 1 completed

### PR DESCRIPTION
**Pull request by shaliniagrawal2512**

### CODE REVIEW

**Comment by garvitchittora** [comment]
@shaliniagrawal2512 repo link is not correct

**Comment by shaliniagrawal2512** [comment]
respected sir,
I checked again and the link is fine may u pls try one more time and if
there is probkem let ke know . I will once again  create the pull request
THANKING YOU
shalini agrawal
IIT2020236

**Comment by garvitchittora** [comment]
@shaliniagrawal2512 I am unable to access that repo make sure ur repo is public

**Comment by shaliniagrawal2512** [comment]
Sorry sir it was private. I have changed the visisbility setting to public.
I hope u can access it now.
Once again sorry for the inconvenience.
Thanking you

**Comment by garvitchittora** [comment]
where is the opening table tag you have closed that, where is the opening one?

**Comment by shaliniagrawal2512** [comment]
Sir, i think it was removed during my work and since it was not causing any
effect to form that is why i don't find that mistake. I have edited my repo
u will find it.
THANKING U. PLS MERGE
Thank you

**Comment by garvitchittora** [comment]
@shaliniagrawal2512 your HTML structure is not correct!!!!!
Correct it first

**Comment by shaliniagrawal2512** [comment]
Sir ,
I have learned html today only so it is not possible to make a perfect
form.
I have checked my html file again and made some changes. We can't learn
evrything in one day so whatever i learned after my first request rejected
is used in this file.
I hope u merge me now
Thanking  you

**Pull request merged**
