### PR TITLE
Done Task 2

### PR DESCRIPTION
**Pull request by Darkknight131714**
Misra Gautam Rajeev
Done Task 2

### CODE REVIEW

**Comment by garvitchittora** [comment]
remove horizontal scrolling

**Comment by Darkknight131714** [comment]
@garvitchittora Removed Horizontal Scrolling

**Comment by garvitchittora** [comment]
@Darkknight131714 it is not responsive!!

**Comment by Darkknight131714** [comment]
@garvitchittora its done now

**Comment by Darkknight131714** [comment]
Sir aap batana agar theek ho website functionality, toh mai apni information daalunga website pe

**Comment by garvitchittora** [comment]
> Sir aap batana agar theek ho website functionality, toh mai apni information daalunga website pe

hm krdo

**Comment by Darkknight131714** [comment]
@garvitchittora  Sir I have entered my information

**Pull request merged**
