### PR TITLE
ABHAY0PARIHAR completed Task-1

### PR DESCRIPTION
**Pull request by A-Spiral-Forge**
Sir, please tell if any changes required. If not, please merge this request.

### CODE REVIEW

**Comment by garvitchittora** [comment]
@ABHAY0PARIHAR  close HTML tag.

**Comment by A-Spiral-Forge** [comment]
Ohh, I foget about it in wrinting this much😅😅

**Comment by A-Spiral-Forge** [comment]
Sir, I updated the file in my repository. Can you please check now.

**Comment by A-Spiral-Forge** [comment]
@garvitchittora  Sir, please checkout my PR.

**Pull request merged**
