### PR TITLE
Ksathwik03 completed task-1

### PR DESCRIPTION
**Pull request by Ksathwik03**

### CODE REVIEW

**Comment by garvitchittora** [comment]
@Ksathwik03 file extension should be html not txt

**Comment by Ksathwik03** [comment]
How can i change it now

**Comment by garvitchittora** [comment]
one way to do this could be to make a new HTML file copy the content and delete the .txt then push your code.

**Comment by Ksathwik03** [comment]
> one way to do this could be to make a new HTML file copy the content and delete the .txt then push your code.

i changed it sir

**Pull request merged**
