### PR TITLE
added Himanshu2608.json

### PR DESCRIPTION
**Pull request by Himanshu2608**

### CODE REVIEW

**Comment by garvitchittora** [comment]
@Himanshu2608 fontawesome icons missing

**Comment by Himanshu2608** [comment]
@garvitchittora sir  can you tell me how to add icons .

**Comment by Himanshu2608** [comment]
@garvitchittora sir i have added the corrected version pls check sir

**Comment by sarthakm21** [comment]
Two form opening tags and two closing body tags are present. Remove the extras

**Comment by garvitchittora** [comment]
pls, make the necessary changes(told above) in your repo before 12 pm otherwise we will close this PR. When you have implemented the changes then comment here only.

**Comment by Himanshu2608** [comment]
@garvitchittora @sarthakm21  Thank you sir I have made the neccesary changes in my repository.

**Comment by garvitchittora** [comment]
@Himanshu2608 confirm checkbox missing

**Comment by Himanshu2608** [comment]
@garvitchittora done sir

**Pull request merged**
