### PR TITLE
supriya-045 completed task1

### PR DESCRIPTION
**Pull request by supriya-045**

### CODE REVIEW

**Comment by garvitchittora** [comment]
@supriya-045 fontawesome icons missing.

**Comment by sarthakm21** [comment]
anchor tags closed twice, action attribute left empty in form element and you cannot have spaces in id names.

**Comment by garvitchittora** [comment]
pls, make the necessary changes(told above) in your repo before 12 pm otherwise we will close this PR. When you have implemented the changes then comment here only.

**Comment by garvitchittora** [comment]
@supriya-045 merging for now but footer should be outside form tag

**Pull request merged**
