### PR TITLE
Completed WebD Task1

### PR DESCRIPTION
**Pull request by PrakCh**

### CODE REVIEW

**Comment by garvitchittora** [comment]
@PrakCh your repo is empty

**Comment by PrakCh** [comment]
> @PrakCh your repo is empty

Sorry Sir, You can check now. I forgot to commit the files last time.

**Comment by garvitchittora** [comment]
@PrakCh fontawesome icons missing

**Comment by PrakCh** [comment]
> @PrakCh fontawesome icons missing

I have commited the required changes. The icons are now visible.

**Pull request merged**
