### PR TITLE
Task-1 completed

### PR DESCRIPTION
**Pull request by anujchaturvedi5748**

### CODE REVIEW

**Comment by garvitchittora** [comment]
@anujchaturvedi5748 your repo is empty.

**Comment by anujchaturvedi5748** [comment]
> @anujchaturvedi5748 your repo is empty.

sir is it ok now ? i imported it

**Comment by garvitchittora** [comment]
@anujchaturvedi5748 where is your HTML file?
Task1 repo should only contain HTML file, not JSON files.

**Comment by anujchaturvedi5748** [comment]
> @anujchaturvedi5748 your repo is empty.
sir i have uploaded my html file in my repo. please check

**Pull request merged**
