### PR TITLE
yashjain94266yj

### PR DESCRIPTION
**Pull request by osho-20**

### CODE REVIEW

**Comment by infern018** [comment]
submit button and made by geekhaven are overlapping

**Comment by sarthakm21** [comment]
Confirm should be a checkbox, not a radio button. Also, you have closed some <tr> tags twice. Review it.

**Comment by garvitchittora** [comment]
@yashjain94266yj  pls make the necessary changes(told above) in your repo before 12 pm otherwise we will close this PR. When you have implemented the changes then comment here only.

**Comment by osho-20** [comment]
okkk sir

**Comment by osho-20** [comment]
@infern018 sir from my side they are not overlapping. when i open it in chrome it is at the bottom of the page

**Comment by osho-20** [comment]
@sarthakm21 sir  i have made changes u can check

**Pull request merged**
