### PR TITLE
New b

### PR DESCRIPTION
**Pull request by codelord09**

### CODE REVIEW

**Comment by garvitchittora** [comment]
@codelord09 fontawesome icons and header missing

**Comment by garvitchittora** [comment]
pls, make the necessary changes(told above) in your repo before 12 pm otherwise we will close this PR. When you have implemented the changes then comment here only.

**Comment by codelord09** [comment]
Sir I have made corresponding changes as mentioned...please consider my pr

**Comment by codelord09** [comment]
Sir consider pr #158..thank you

**Comment by codelord09** [comment]
Sir why do you closed this?

**Pull request closed without merging**
