### PR TITLE
Web Dev Task-01

### PR DESCRIPTION
**Pull request by 21-kunal**
Hi ,
Kunal Prajapati here . Completed the task-01 of web dev.

### CODE REVIEW

**Comment by garvitchittora** [comment]
@21-kunal footer missing

**Comment by 21-kunal** [comment]
Sir please check it again i try to complete the task

**Comment by garvitchittora** [comment]
@21-kunal fontawesome icons not visible and file extension should be .json not .json.txt

**Comment by garvitchittora** [comment]
pls, make the necessary changes(told above) in your repo before 12 pm otherwise we will close this PR. When you have implemented the changes then comment here only.

**Pull request closed without merging**
