### PR TITLE
task 1 completed sir

### PR DESCRIPTION
**Pull request by geek-dotm**

### CODE REVIEW

**Comment by garvitchittora** [comment]
PR after 12 so rejected!!

**Comment by geek-dotm** [comment]
> PR after 12 so rejected!!

sir I did it before 12 
some bracket error occured sir I am very sorry sir 
pleas mearge it award me points

**Comment by garvitchittora** [comment]
> > PR after 12 so rejected!!
> 
> sir I did it before 12
> some bracket error occured sir I am very sorry sir
> pleas mearge it award me points

sorry but now also your code is incomplete no body tag is there.

**Comment by geek-dotm** [comment]
> > > PR after 12 so rejected!!
> > 
> > 
> > sir I did it before 12
> > some bracket error occured sir I am very sorry sir
> > pleas mearge it award me points
> 
> sorry but now also your code is incomplete no body tag is there.

sir can u please join the discord voice

**Comment by geek-dotm** [comment]
sir please check it once

**Comment by geek-dotm** [comment]
and very sorry for those mistakes sirrr............

**Comment by garvitchittora** [comment]
You will get 0 points because of submission after the deadline!!

**Pull request merged**
